-- MySQL Script generated by MySQL Workbench
-- Fri Mar  5 17:40:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PointOfSale
-- -----------------------------------------------------

-- ---------------------------------- MySQL Script generated by MySQL Workbench
-- Mon Mar  8 18:44:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PointOfSale
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PointOfSale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PointOfSale` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `PointOfSale` ;

-- -----------------------------------------------------
-- Table `PointOfSale`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(45) NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `stock` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `price` DECIMAL NOT NULL,
  `status` ENUM('ACTIVE', 'DESACTIVE') NULL DEFAULT 'DESACTIVE',
  `category_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  INDEX `fk_products_categories_idx` (`category_id` ASC) ,
  INDEX `fk_products_providers1_idx` (`provider_id` ASC) ,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `PointOfSale`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `PointOfSale`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `create_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `PointOfSale`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tax` VARCHAR(45) NULL,
  `total` DECIMAL NULL,
  `status` ENUM('VALID', 'CANCEL') NULL DEFAULT 'VALID',
  `picture` VARCHAR(45) NULL,
  `provider_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchases_providers1_idx` (`provider_id` ASC) ,
  INDEX `fk_purchases_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_purchases_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `PointOfSale`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchases_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `PointOfSale`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`purchase_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`purchase_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `price` DECIMAL NULL,
  `shopping_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_details_purchases1_idx` (`shopping_id` ASC) ,
  INDEX `fk_purchase_details_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_purchase_details_purchases1`
    FOREIGN KEY (`shopping_id`)
    REFERENCES `PointOfSale`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_details_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `PointOfSale`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tax` VARCHAR(45) NULL,
  `total` DECIMAL NULL,
  `status` ENUM('VALID', 'CANCEL') NULL DEFAULT 'VALID',
  `user_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_users1_idx` (`user_id` ASC) ,
  INDEX `fk_sales_clients1_idx` (`client_id` ASC) ,
  CONSTRAINT `fk_sales_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `PointOfSale`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `PointOfSale`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PointOfSale`.`sale_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`sale_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `price` DECIMAL NULL,
  `discount` DECIMAL NULL,
  `sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_details_sales1_idx` (`sale_id` ASC) ,
  INDEX `fk_sale_details_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_sale_details_sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `PointOfSale`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_details_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `PointOfSale`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
---------------------
-- Schema PointOfSale
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PointOfSale` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `PointOfSale` ;

-- -----------------------------------------------------
-- Table `PointOfSale`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `stock` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `price` DECIMAL NULL,
  `status` ENUM('ACTIVE', 'DESACTIVE') NULL DEFAULT 'DESACTIVE',
  `category_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) ,
  INDEX `fk_products_categories_idx` (`category_id` ASC) ,
  INDEX `fk_products_providers1_idx` (`provider_id` ASC) ,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `PointOfSale`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `PointOfSale`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `create_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `PointOfSale`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_date` VARCHAR(45) NULL,
  `tax` VARCHAR(45) NULL,
  `total` DECIMAL NULL,
  `status` ENUM('VALID', 'CANCEL') NULL DEFAULT 'VALID',
  `picture` VARCHAR(45) NULL,
  `provider_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchases_providers1_idx` (`provider_id` ASC) ,
  INDEX `fk_purchases_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_purchases_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `PointOfSale`.`providers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchases_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `PointOfSale`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`purchase_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`purchase_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `price` DECIMAL NULL,
  `shopping_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_details_purchases1_idx` (`shopping_id` ASC) ,
  INDEX `fk_purchase_details_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_purchase_details_purchases1`
    FOREIGN KEY (`shopping_id`)
    REFERENCES `PointOfSale`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_details_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `PointOfSale`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PointOfSale`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tax` VARCHAR(45) NULL,
  `total` DECIMAL NULL,
  `status` ENUM('VALID', 'CANCEL') NULL DEFAULT 'VALID',
  `user_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_users1_idx` (`user_id` ASC) ,
  INDEX `fk_sales_clients1_idx` (`client_id` ASC) ,
  CONSTRAINT `fk_sales_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `PointOfSale`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `PointOfSale`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `PointOfSale`.`sale_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PointOfSale`.`sale_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `price` DECIMAL NULL,
  `discount` DECIMAL NULL,
  `sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_details_sales1_idx` (`sale_id` ASC) ,
  INDEX `fk_sale_details_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_sale_details_sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `PointOfSale`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_details_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `PointOfSale`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
